version: "3.8"

networks:
    bankruptcy-network:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: bankruptcy-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - bankruptcy-network

    php:
        container_name: bankruptcy-php
        restart: unless-stopped
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./backend:/var/www/html
            - ./Makefile:/var/www/html/Makefile:ro
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
        environment:
            DATABASE_URL: "mysql://bankruptcy:bankruptcy@mysql:3306/bankruptcy?serverVersion=8.0"
            APP_ENV: dev
            APP_SECRET: "change_me_in_production"
        networks:
            - bankruptcy-network

    mysql:
        image: mysql:8.0
        container_name: bankruptcy-mysql
        restart: unless-stopped
        command: --max_allowed_packet=16M --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/var/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bankruptcy
            MYSQL_USER: bankruptcy
            MYSQL_PASSWORD: bankruptcy
        networks:
            - bankruptcy-network

    frontend:
        container_name: bankruptcy-frontend
        build:
            context: ./frontend
            dockerfile: ../docker/frontend/Dockerfile
            args:
                VITE_API_URL: http://api.localhost
        restart: unless-stopped
        expose:
            - "5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        networks:
            - bankruptcy-network
        stdin_open: true
        tty: true