version: "3.8"

networks:
  bankruptcy-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: bankruptcy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - php
    networks:
      - bankruptcy-network

  php:
    container_name: bankruptcy-php
    restart: unless-stopped
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/config/php.production.ini:/usr/local/etc/php/php.ini
    networks:
      - bankruptcy-network

  mysql:
    image: mysql:8.0
    container_name: bankruptcy-mysql
    restart: unless-stopped
    command: --max_allowed_packet=16M --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: bankruptcy
      MYSQL_USER: bankruptcy
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - bankruptcy-network

  frontend:
    container_name: bankruptcy-frontend
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        VITE_API_URL: https://api.littlewell-app.work
    restart: unless-stopped
    networks:
      - bankruptcy-network

volumes:
  mysql_data: