doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
    orm:
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: "App\\Entity"
                alias: App
